version: '3'

services:
  node-server:
    build: .
    container_name: node-server
    entrypoint: ./.docker/entrypoint.sh
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '3003:3003'
     